### PR TITLE
Create a cheat sheet for Git

### PR DESCRIPTION
**Pull request by albertwang21**
Create a cheat sheet git.txt for Git.

### CODE REVIEW

**Comment by skywind3000** [comment]
帅，麻烦修改下 readme.md 把该文件添加到 tools 下面

**Comment by albertwang21** [comment]
README.md file updated.

**Comment by skywind3000** [comment]
README.md 你改了些啥啊？为啥 diff 看下来你改了所有内容？

**Comment by albertwang21** [comment]
仅在“开发工具”栏目下增加 - [Git](tools/git.txt)。不知为何 diff 显示为修改了所有内容。

**Comment by albertwang21** [comment]
当在线编辑 README.md 时，github 会提示 “We’ve detected the file has mixed line endings. When you commit changes we will normalize them to Windows-style (CRLF).” 我猜测 <diff 显示修改了全部内容> 是由这个引起的。

**Comment by albertwang21** [comment]
After accepting this pull request, you can try 'unix2dos -k README.md' at your local directory and push this change to the remote repository to fix this problem.

**Pull request merged**
